source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'Firebase/Auth', '8.1.1'
  pod 'Firebase/Core', '8.1.1'
  pod 'Firebase/Database', '8.1.1'
end
target 'Unity-iPhone' do
end
use_frameworks!
